title: "Jennefer Boudreau"
email: 12thandclark@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 In the works
baseurl: "/" 
url: "https://Jennormous.github.io/" 
twitter_username: jennormous
github_username:  Jennormous

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
