title: "Jennefer Boudreau"
email: "12thandclark@gmail.com"
description: "In the works"
baseurl: "/"
url: "https://Jennormous.github.io/"
twitter_username: jennormous
github_username: Jennormous

sass:
  sass_dir: _sass

icon: ./assets/img/jboudreau.jpg
